version: '3'
services:
  app:
    image: kozlovsv78/parking
    container_name: parking
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - ./:/opt/parking/
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1