version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
#      - run: |
#          docker-compose -f docker-compose.ci.yml build
#          docker login -u $DOCKER_USER -p $DOCKER_PASS
#          docker-compose -f docker-compose.ci.yml push --ignore-push-failures
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Copy docker-compose
          command: scp docker-compose.ci.yml $SSH_USER@$SSH_HOST:/opt/parking/docker-compose.yml
#      - run:
#          name: Deploy Over SSH
#          command: |
#            ssh $SSH_USER@$SSH_HOST << EOF
#            docker-compose -f docker-compose.ci.yml pull
#            docker-compose -f docker-compose.ci.yml -d up
#            EOF
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master # only deploy on the master branch