version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker-compose -f docker-compose.ci.yml build
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose -f docker-compose.ci.yml push --ignore-push-failures
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Make Project Dir
          command: ssh $SSH_USER@$SSH_HOST mkdir -p $REMOTE_APP_DIR
      - run:
          name: Copy docker-compose
          command: scp docker-compose.ci.yml $SSH_USER@$SSH_HOST:$REMOTE_APP_DIR
      - run:
          name: Make env File
          command: |
            ssh $SSH_USER@$SSH_HOST << EOF
            mv -f $REMOTE_APP_DIR\docker-compose.ci.yml $REMOTE_APP_DIR\docker-compose.yml
            printf "UFANET_USER_NAME=$UFANET_USER_NAME\nUFANET_USER_PASSWORD=$UFANET_USER_PASSWORD" > $REMOTE_APP_DIR.env
            EOF
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST << EOF
            cd $REMOTE_APP_DIR
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose pull
            docker-compose up -d
            docker system prune -a -f
            EOF
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master # only deploy on the master branch