version: 2

 jobs:
   build:
     #...
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "cd /; mkdir project"
 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only deploy once build job has completed
           filters:
             branches:
               only: master # only deploy on the master branch
               
               # git clone https://github.com/kozlovsv/parking_search.git